//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ichosys.DataModel.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataModelTestString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataModelTestString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ichosys.DataModel.Tests.Resources.DataModelTestString", typeof(DataModelTestString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary owner(s) of the account.
        /// </summary>
        public static string Account_AccountHolder_Description {
            get {
                return ResourceManager.GetString("Account_AccountHolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account holder.
        /// </summary>
        public static string Account_AccountHolder_Name {
            get {
                return ResourceManager.GetString("Account_AccountHolder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account numbers.
        /// </summary>
        public static string Account_AccountNumber_Plural {
            get {
                return ResourceManager.GetString("Account_AccountNumber_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Account_AccountNumber_PluralArticle {
            get {
                return ResourceManager.GetString("Account_AccountNumber_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account number.
        /// </summary>
        public static string Account_AccountNumber_Singular {
            get {
                return ResourceManager.GetString("Account_AccountNumber_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Account_AccountNumber_SingularArticle {
            get {
                return ResourceManager.GetString("Account_AccountNumber_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts.
        /// </summary>
        public static string Account_Plural {
            get {
                return ResourceManager.GetString("Account_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Account_PluralArticle {
            get {
                return ResourceManager.GetString("Account_PluralArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string Account_Singular {
            get {
                return ResourceManager.GetString("Account_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string Account_SingularArticle {
            get {
                return ResourceManager.GetString("Account_SingularArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account code.
        /// </summary>
        public static string AccountObject_AccountObjectCode {
            get {
                return ResourceManager.GetString("AccountObject_AccountObjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custodian/bank identifier for the account..
        /// </summary>
        public static string Display_AccountNumber_Description {
            get {
                return ResourceManager.GetString("Display_AccountNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        public static string Display_AccountNumber_GroupName {
            get {
                return ResourceManager.GetString("Display_AccountNumber_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string Display_AccountNumber_Name {
            get {
                return ResourceManager.GetString("Display_AccountNumber_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account number.
        /// </summary>
        public static string Display_AccountNumber_Prompt {
            get {
                return ResourceManager.GetString("Display_AccountNumber_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acct. #.
        /// </summary>
        public static string Display_AccountNumber_ShortName {
            get {
                return ResourceManager.GetString("Display_AccountNumber_ShortName", resourceCulture);
            }
        }
    }
}
